language: java
jdk:
  - oraclejdk9
  - openjdk9
install:
  - echo hello
jobs:
  include:
    stage: test
      script:
        - echo world test
    stage: build
      script:
        - echo world deploy
